import type {
  ArtifactBrandingOptions,
  ArtifactBrandingRecord,
  ArtifactBrandingVisibility,
} from './types';

export const ARTIFACT_BRANDING = {
  version: 1,
  brandName: 'Symposium AI',
  attribution: 'Created with Symposium AI',
  generatedBy: 'Generated by Symposium AI',
  url: 'https://symposiumai.app',
  hostLabel: 'symposiumai.app',
  logoPath: '/branding/symposium-logo.svg',
  colors: {
    text: '#334155',
    muted: '#64748b',
    border: '#e2e8f0',
    background: '#f8fafc',
  },
  logoSvg: `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="1024" height="1024" fill="#1A1A1A" rx="81.92" ry="81.92"/>
  <circle cx="686.08" cy="512" r="172.032" fill="#C15F3C" opacity="0.15"/>
  <circle cx="686.08" cy="512" r="163.84" fill="#C15F3C" opacity="0.65"/>
  <circle cx="645.3530166581517" cy="623.8964670942328" r="172.032" fill="#10A37F" opacity="0.15"/>
  <circle cx="645.3530166581517" cy="623.8964670942328" r="163.84" fill="#10A37F" opacity="0.65"/>
  <circle cx="542.2286747682592" cy="683.4353336443652" r="172.032" fill="#4888F8" opacity="0.15"/>
  <circle cx="542.2286747682592" cy="683.4353336443652" r="163.84" fill="#4888F8" opacity="0.65"/>
  <circle cx="424.96000000000004" cy="662.7577022907951" r="172.032" fill="#20808D" opacity="0.15"/>
  <circle cx="424.96000000000004" cy="662.7577022907951" r="163.84" fill="#20808D" opacity="0.65"/>
  <circle cx="348.41830857358906" cy="571.5388665501324" r="172.032" fill="#FA520F" opacity="0.15"/>
  <circle cx="348.41830857358906" cy="571.5388665501324" r="163.84" fill="#FA520F" opacity="0.65"/>
  <circle cx="348.41830857358906" cy="452.4611334498676" r="172.032" fill="#FF7759" opacity="0.15"/>
  <circle cx="348.41830857358906" cy="452.4611334498676" r="163.84" fill="#FF7759" opacity="0.65"/>
  <circle cx="424.9599999999999" cy="361.24229770920493" r="172.032" fill="#0F6FFF" opacity="0.15"/>
  <circle cx="424.9599999999999" cy="361.24229770920493" r="163.84" fill="#0F6FFF" opacity="0.65"/>
  <circle cx="542.2286747682592" cy="340.5646663556348" r="172.032" fill="#4D6BFE" opacity="0.15"/>
  <circle cx="542.2286747682592" cy="340.5646663556348" r="163.84" fill="#4D6BFE" opacity="0.65"/>
  <circle cx="645.3530166581517" cy="400.10353290576717" r="172.032" fill="#1DA1F2" opacity="0.15"/>
  <circle cx="645.3530166581517" cy="400.10353290576717" r="163.84" fill="#1DA1F2" opacity="0.65"/>
  <circle cx="512" cy="512" r="61.44" fill="#1A1A1A"/>
</svg>`,
} as const;

export const DEFAULT_ARTIFACT_BRANDING_OPTIONS: Required<ArtifactBrandingOptions> = {
  visibility: 'visible',
  includeLogo: true,
  includeUrl: true,
};

export const HTML_BRANDING_MARKER = 'data-symposium-artifact-branding';

export function normalizeArtifactBrandingOptions(
  options?: ArtifactBrandingOptions | null,
): Required<ArtifactBrandingOptions> {
  return {
    ...DEFAULT_ARTIFACT_BRANDING_OPTIONS,
    ...(options ?? {}),
  };
}

export function isVisibleBranding(options?: ArtifactBrandingOptions | null): boolean {
  return normalizeArtifactBrandingOptions(options).visibility === 'visible';
}

export function shouldWriteBrandingMetadata(options?: ArtifactBrandingOptions | null): boolean {
  const visibility = normalizeArtifactBrandingOptions(options).visibility;
  return visibility === 'visible' || visibility === 'metadata';
}

export function createArtifactBrandingRecord(
  options?: ArtifactBrandingOptions | null,
  appliedAt: Date = new Date(),
): ArtifactBrandingRecord {
  const resolved = normalizeArtifactBrandingOptions(options);
  return {
    version: ARTIFACT_BRANDING.version,
    visibility: resolved.visibility,
    brandName: ARTIFACT_BRANDING.brandName,
    attribution: ARTIFACT_BRANDING.attribution,
    url: ARTIFACT_BRANDING.url,
    logoPath: ARTIFACT_BRANDING.logoPath,
    appliedAt: appliedAt.toISOString(),
  };
}

export function formatBrandingLine(options?: ArtifactBrandingOptions | null): string {
  const resolved = normalizeArtifactBrandingOptions(options);
  if (!resolved.includeUrl) return ARTIFACT_BRANDING.attribution;
  return `${ARTIFACT_BRANDING.attribution} | ${ARTIFACT_BRANDING.hostLabel}`;
}

export function svgToDataUri(svg = ARTIFACT_BRANDING.logoSvg): string {
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

function htmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function injectBeforeBodyClose(html: string, insertion: string): string {
  const bodyCloseIdx = html.lastIndexOf('</body>');
  if (bodyCloseIdx !== -1) {
    return html.slice(0, bodyCloseIdx) + insertion + html.slice(bodyCloseIdx);
  }

  const htmlCloseIdx = html.lastIndexOf('</html>');
  if (htmlCloseIdx !== -1) {
    return html.slice(0, htmlCloseIdx) + insertion + html.slice(htmlCloseIdx);
  }

  return `${html}${insertion}`;
}

function injectIntoHead(html: string, insertion: string): string {
  const headIdx = html.indexOf('<head>');
  if (headIdx !== -1) {
    const insertPos = headIdx + '<head>'.length;
    return html.slice(0, insertPos) + insertion + html.slice(insertPos);
  }

  const htmlIdx = html.indexOf('<html');
  if (htmlIdx !== -1) {
    const closeTag = html.indexOf('>', htmlIdx);
    if (closeTag !== -1) {
      const insertPos = closeTag + 1;
      return html.slice(0, insertPos) + `<head>${insertion}</head>` + html.slice(insertPos);
    }
  }

  return `${insertion}${html}`;
}

function buildHtmlBrandingStyle(): string {
  return `<style data-symposium-artifact-branding-style>
.symposium-artifact-branding{box-sizing:border-box;width:100%;margin:32px 0 0;padding:12px 16px;border-top:1px solid ${ARTIFACT_BRANDING.colors.border};background:${ARTIFACT_BRANDING.colors.background};color:${ARTIFACT_BRANDING.colors.muted};font:12px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;text-align:center;letter-spacing:0}
.symposium-artifact-branding a{color:${ARTIFACT_BRANDING.colors.text};text-decoration:none;font-weight:600}
.symposium-artifact-branding__inner{display:inline-flex;align-items:center;justify-content:center;gap:8px;max-width:100%}
.symposium-artifact-branding__logo{width:18px;height:18px;border-radius:4px;display:block;flex:0 0 auto}
</style>`;
}

function buildHtmlBrandingFooter(options?: ArtifactBrandingOptions | null): string {
  const resolved = normalizeArtifactBrandingOptions(options);
  const logo = resolved.includeLogo
    ? `<img class="symposium-artifact-branding__logo" alt="" src="${svgToDataUri()}" />`
    : '';
  const line = htmlEscape(formatBrandingLine(options));
  const url = htmlEscape(ARTIFACT_BRANDING.url);

  return `<footer ${HTML_BRANDING_MARKER}="visible" class="symposium-artifact-branding"><div class="symposium-artifact-branding__inner">${logo}<a href="${url}" target="_blank" rel="noopener noreferrer">${line}</a></div></footer>`;
}

export function applyBrandingToHtml(
  html: string,
  options?: ArtifactBrandingOptions | null,
): string {
  if (!isVisibleBranding(options) || !html.trim()) return html;
  if (html.includes(`${HTML_BRANDING_MARKER}="visible"`)) return html;

  const withStyle = html.includes('data-symposium-artifact-branding-style')
    ? html
    : injectIntoHead(html, buildHtmlBrandingStyle());

  return injectBeforeBodyClose(withStyle, buildHtmlBrandingFooter(options));
}

export function toArtifactBrandingVisibility(value: unknown): ArtifactBrandingVisibility {
  if (value === 'metadata' || value === 'off') return value;
  return 'visible';
}
