export const DEBATE_TOPICS = [
  // Fun & Quirky
  "Is a hot dog a sandwich?",
  "Is pineapple on pizza acceptable?",
  "Should toilet paper hang over or under?",
  "Is water wet?",
  "Are birds real or government drones?",
  "Is cereal soup?",
  "Should you shower in the morning or at night?",
  "Is math invented or discovered?",
  "Can fish be considered pets if they don't know you exist?",
  "Is it acceptable to put ketchup on eggs?",
  "Which came first, the chicken or the egg?",
  "Is Die Hard a Christmas movie?",
  "Should you eat pizza with a fork?",
  "Is it gif or jif?",
  "Is it okay to double dip?",
  "Should you put milk or cereal first?",
  "Are tomatoes fruits or vegetables?",
  "Is a taco a sandwich?",
  "Should you wash jeans?",
  "Is it acceptable to wear socks with sandals?",
  "Should books be adapted into movies?",
  "Is it better to be early or fashionably late?",
  "Should you fold or crumple toilet paper?",
  "Is it okay to recline your airplane seat?",
  "Should you tip for takeout?",
  "Is breakfast for dinner acceptable?",
  "Should you sleep with your bedroom door open or closed?",
  "Is it okay to wear pajamas in public?",
  "Should you squeeze toothpaste from the middle or bottom?",
  "Is it better to be too hot or too cold?",
  
  // Technology & Future
  "Are we living in a simulation?",
  "Should AI have rights?",
  "Is time travel possible?",
  "Is artificial intelligence moving too fast for society?",
  "Should social media be regulated?",
  "Is remote work better than office work?",
  "Are NFTs the future or a fad?",
  "Should we colonize Mars?",
  "Will robots replace most human jobs?",
  "Should there be a universal basic income?",
  "Is privacy dead in the digital age?",
  "Should we fear quantum computing?",
  "Will cryptocurrency replace traditional money?",
  "Should there be limits on genetic engineering?",
  "Is the metaverse the future of social interaction?",
  "Should we build a Dyson sphere?",
  "Will we achieve immortality through technology?",
  "Should we make contact with aliens?",
  "Is consciousness transferable to machines?",
  "Should we terraform other planets?",
  
  // Philosophy & Life
  "Is free will an illusion?",
  "Does true altruism exist?",
  "Is ignorance bliss?",
  "Can money buy happiness?",
  "Is there objective morality?",
  "Do we live in the best possible timeline?",
  "Is reality subjective or objective?",
  "Does life have inherent meaning?",
  "Is it better to be feared or loved?",
  "Can you change your personality?",
  "Is talent or hard work more important?",
  "Should you follow your passion or be practical?",
  "Is it better to have loved and lost?",
  "Do soulmates exist?",
  "Is karma real?",
  "Can people truly change?",
  "Is there life after death?",
  "Does everything happen for a reason?",
  "Is human nature good or evil?",
  "Is perfection achievable?",
  
  // Society & Culture
  "Should tipping culture be abolished?",
  "Is cancel culture going too far?",
  "Should college be free?",
  "Is social media making us less social?",
  "Should voting be mandatory?",
  "Is the education system outdated?",
  "Should there be term limits for all politicians?",
  "Is capitalism the best economic system?",
  "Should we have a four-day work week?",
  "Is fame worth pursuing?",
  "Should everyone learn to code?",
  "Is traditional media dead?",
  "Should we abolish daylight saving time?",
  "Is the nuclear family model outdated?",
  "Should there be a maximum wage?",
  "Is patriotism important?",
  "Should we have open borders?",
  "Is the justice system fair?",
  "Should we lower the voting age?",
  "Is meritocracy a myth?",
  
  // Science & Nature
  "Is Pluto a planet?",
  "Are we alone in the universe?",
  "Is climate change reversible?",
  "Should we bring back extinct species?",
  "Is nuclear energy the solution?",
  "Are GMOs safe?",
  "Is evolution just a theory?",
  "Should we edit human genes?",
  "Is there a multiverse?",
  "Can we predict the future?",
  "Is consciousness unique to humans?",
  "Should we experiment on animals?",
  "Is the universe infinite?",
  "Will we run out of fresh water?",
  "Is solar power the future?",
  "Should we mine asteroids?",
  "Can we reverse aging?",
  "Is teleportation possible?",
  "Should we create artificial life?",
  "Is the Big Bang theory correct?",
  
  // Entertainment & Pop Culture
  "Are remakes better than originals?",
  "Is binge-watching unhealthy?",
  "Should celebrities stay out of politics?",
  "Are video games art?",
  "Is streaming killing cinema?",
  "Should there be age limits on social media?",
  "Are influencers good role models?",
  "Is reality TV harmful to society?",
  "Should we separate art from the artist?",
  "Are spoilers really that bad?",
  "Is physical media dead?",
  "Should there be a limit on sequels?",
  "Are memes a form of art?",
  "Is autotune cheating?",
  "Should concerts have phone-free zones?",
  "Are podcasts replacing traditional media?",
  "Is it okay to watch movies on your phone?",
  "Should there be an Oscar for stunt work?",
  "Are superhero movies oversaturated?",
  "Is vinyl better than digital?",
  
  // Health & Lifestyle
  "Is veganism the future?",
  "Should we ban fast food?",
  "Is CrossFit a cult?",
  "Are supplements necessary?",
  "Is coffee good or bad for you?",
  "Should we normalize naps at work?",
  "Is 10,000 steps a day necessary?",
  "Are gym memberships worth it?",
  "Is intermittent fasting healthy?",
  "Should we ban smoking completely?",
  "Is organic food worth the price?",
  "Are standing desks better?",
  "Should mental health days be mandatory?",
  "Is multitasking a myth?",
  "Should we limit screen time?",
  "Is meditation overrated?",
  "Are cold showers beneficial?",
  "Should we ban energy drinks?",
  "Is the 8-hour sleep rule universal?",
  "Are cheat days counterproductive?",
  
  // Relationships & Social
  "Can men and women just be friends?",
  "Is online dating ruining romance?",
  "Should you remain friends with your ex?",
  "Is marriage outdated?",
  "Are open relationships sustainable?",
  "Should couples have joint bank accounts?",
  "Is it okay to keep secrets in a relationship?",
  "Should you date within your friend group?",
  "Is the friendzone real?",
  "Are long-distance relationships worth it?",
  "Should you live together before marriage?",
  "Is it okay to go through your partner's phone?",
  "Should couples have separate bedrooms?",
  "Is love at first sight real?",
  "Should you change for your partner?",
  "Are age gap relationships problematic?",
  "Is it okay to date a coworker?",
  "Should you tell your partner everything?",
  "Is jealousy healthy in small doses?",
  "Can you love two people at once?",
];

// AI_PERSONALITIES has been moved to src/config/personalities.ts for unified personality system

export const DEBATE_REACTIONS = [
  { emoji: '😂', label: 'Hilarious' },
  { emoji: '🤔', label: 'Good point' },
  { emoji: '😱', label: 'Mind blown' },
  { emoji: '👏', label: 'Brilliant' },
  { emoji: '🙄', label: 'Really?' },
  { emoji: '🔥', label: 'Burn!' },
];