name: Continuous Integration

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript compilation
        run: npx tsc --noEmit

      - name: ESLint check
        run: npm run lint

      - name: Run tests (if available)
        run: npm test -- --passWithNoTests
        continue-on-error: true

      - name: Check bundle size
        run: |
          npm run build:analyze || true
        continue-on-error: true